php-version = "8.1.0"

[source]
workspace = "."
paths = [
    "./src", 
    "./test", 
    "./examples",
]
includes = [
    "./vendor",
]

[formatter]
print-width = 80
tab-width = 4
use-tabs = false
end-of-line = "lf"
single-quote = false
trailing-comma = true
remove-trailing-close-tag = true

[linter]
integrations = [
    "phpunit",
]

[linter.rules]
# Best Practices
combine-consecutive-issets = { enabled = true }
loop-does-not-iterate = { enabled = true }
no-ini-set = { enabled = true }
no-sprintf-concat = { enabled = false }
prefer-arrow-function = { enabled = true }
prefer-early-continue = { enabled = true }
prefer-first-class-callable = { enabled = false }
prefer-static-closure = { enabled = true }
prefer-while-loop = { enabled = true }
require-namespace = { enabled = true }
use-compound-assignment = { enabled = true }
yoda-conditions = { enabled = true }

# Clarity
explicit-octal = { enabled = true }
instanceof-stringable = { enabled = true }
literal-named-argument = { enabled = false }
no-empty = { enabled = true }
no-hash-emoji = { enabled = true }
no-multi-assignments = { enabled = true }
no-nested-ternary = { enabled = false }
no-shorthand-ternary = { enabled = true }
no-variable-variable = { enabled = true }
readable-literal = { enabled = true }
str-contains = { enabled = true }
str-starts-with = { enabled = true }
tagged-fixme = { enabled = false }
tagged-todo = { enabled = false }
valid-docblock = { enabled = true }

# Consistency
ambiguous-function-call = { enabled = true }
array-style = { enabled = true }
assertion-style = { enabled = true } # PHPUnit
block-statement = { enabled = false }
braced-string-interpolation = { enabled = true }
class-name = { enabled = true }
constant-name = { enabled = true }
enum-name = { enabled = true }
function-name = { enabled = true }
interface-name = { enabled = true }
lowercase-keyword = { enabled = true }
lowercase-type-hint = { enabled = true }
no-alias-function = { enabled = true }
no-hash-comment = { enabled = true }
no-php-tag-terminator = { enabled = true }
no-trailing-space = { enabled = true }
property-name = { enabled = true }
trait-name = { enabled = true }
variable-name = { enabled = true }

# Correctness
assert-description = { enabled = true }
constant-type = { enabled = true }
identity-comparison = { enabled = true }
ineffective-format-ignore-next = { enabled = true }
ineffective-format-ignore-region = { enabled = true }
invalid-open-tag = { enabled = true }
no-assign-in-condition = { enabled = true }
no-boolean-literal-comparison = { enabled = false }
no-empty-catch-clause = { enabled = true }
parameter-type = { enabled = true }
property-type = { enabled = true }
return-type = { enabled = true }
strict-assertions = { enabled = true } # PHPUnit
strict-behavior = { enabled = true }
strict-types = { enabled = true }
use-specific-assertions = { enabled = true } # PHPUnit

# Deprecation
explicit-nullable-param = { enabled = true }
no-underscore-class = { enabled = true }
no-void-reference-return = { enabled = false }
optional-param-order = { enabled = true }

# Maintainability
cyclomatic-complexity = { enabled = true }
excessive-nesting = { enabled = true }
excessive-parameter-list = { enabled = true }
halstead = { enabled = true }
kan-defect = { enabled = true }
no-boolean-flag-parameter = { enabled = false }
no-else-clause = { enabled = false }
no-goto = { enabled = true }
too-many-enum-cases = { enabled = false }
too-many-methods = { enabled = false }
too-many-properties = { enabled = false }

# Redundancy
constant-condition = { enabled = true }
inline-variable-return = { enabled = true }
no-closing-tag = { enabled = true }
no-empty-comment = { enabled = true }
no-empty-loop = { enabled = true }
no-noop = { enabled = true }
no-protected-in-final = { enabled = true }
no-redundant-block = { enabled = true }
no-redundant-continue = { enabled = true }
no-redundant-file = { enabled = true }
no-redundant-final = { enabled = true }
no-redundant-label = { enabled = true }
no-redundant-literal-return = { enabled = true }
no-redundant-math = { enabled = true }
no-redundant-method-override = { enabled = true }
no-redundant-nullsafe = { enabled = true }
no-redundant-parentheses = { enabled = true }
no-redundant-readonly = { enabled = true }
no-redundant-string-concat = { enabled = true }
no-redundant-use = { enabled = true }
no-redundant-write-visibility = { enabled = true }
no-redundant-yield-from = { enabled = true }
no-self-assignment = { enabled = true }

# Safety
no-error-control-operator = { enabled = true }
no-eval = { enabled = true }
no-ffi = { enabled = false }
no-global = { enabled = true }
no-request-variable = { enabled = true }
no-shell-execute-string = { enabled = false }
no-unsafe-finally = { enabled = true }

# Security
disallowed-functions = { enabled = true }
no-debug-symbols = { enabled = true }
no-insecure-comparison = { enabled = true }
no-literal-password = { enabled = true }
no-short-opening-tag = { enabled = true }
no-unescaped-output = { enabled = true }
require-preg-quote-delimiter = { enabled = true }
sensitive-parameter = { enabled = true }
tainted-data-to-sink = { enabled = true }

[analyzer]
excludes = [
    "./vendor",
]
find-unused-expressions = true
find-unused-definitions = true
analyze-dead-code = true
memoize-properties = true
allow-possibly-undefined-array-keys = false
check-throws = true
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = false
check-missing-type-hints = true
check-closure-missing-type-hints = true
check-arrow-function-missing-type-hints = true
register-super-globals = true
trust-existence-checks = false
check-property-initialization = true
check-use-statements = true
